apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-app-deployment
  labels:
    app: sample-netcore-application
spec:
  replicas: 2
  selector:
    matchLabels:
      name: netcore-app
      app: netcore-application
  template:
    metadata:
      name: netcore-app-pod
      labels:
        name: netcore-app-pod
        app: sample-netcore-application
    spec:
      containers:
      - name: netcore-app
        image: mohanaveluk/aspcoreondocker:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
